services:
  oven-backend-dev:
    build:
      context: ../ovenPlatform-be
      dockerfile: Dockerfile.dev
    image: oven-backend-dev:1.5.0
    container_name: oven-backend-dev
    ports:
      - "3001:3000"
    volumes:
      - ../ovenPlatform-be:/app
      - /app/node_modules
    networks:
      - ovendevelop-net

  oven-frontend-dev:
    build:
      context: ../ovenPlatform-web
      dockerfile: Dockerfile.dev
    image: oven-frontend-dev:1.5.0
    container_name: oven-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - ../ovenPlatform-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - VITE_API_URL=http://custom-api:3000
    env_file:
      - ../ovenPlatform-web/.env.development
    networks:
      - ovendevelop-net

networks:
  ovendevelop-net:
    name: ovendevelop-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.20.0/27
