services:
  # Backend Service
  oven-backend:
    build:
      context: ../ovenPlatform-be
      dockerfile: Dockerfile.prod
    image: oven-backend-prod:1.0.0
    container_name: oven-backend-prod
    restart: unless-stopped
    ports:
      - "4172:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ../ovenPlatform-be/.env.production
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    networks:
      - oven-network

  # Frontend Service
  oven-frontend:
    build:
      context: ../ovenPlatform-web
      dockerfile: Dockerfile.prod
    image: oven-frontend-prod:1.0.0
    container_name: oven-frontend-prod
    restart: unless-stopped
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      # - VITE_API_URL=${BACKEND_URL:-http://oven-backend:3000}
    env_file:
      - ../ovenPlatform-web/.env
      - ../ovenPlatform-web/.env.production
    depends_on:
      - oven-backend
        # condition: service_healthy
    networks:
      - oven-network

  # Proxy Service (Nginx)
  # oven-proxy:
  #   image: nginx:1.25-alpine
  #   container_name: oven-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./nginx/certs:/etc/nginx/certs:ro
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - oven-frontend
  #     - oven-backend
  #   networks:
  #     - oven-network

networks:
  oven-network:
    driver: bridge

# volumes:
#   nginx-logs:
