services:
  oven-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: oven-frontend-dev:0.0.1
    container_name: oven-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      # - VITE_API_URL=http://custom-api:3000
    env_file:
      - ./.env
      - ./.env.development
      # - ./.env.local
    stdin_open: true
    tty: true