
FROM node:22.15.0-alpine3.20 AS builder
WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

RUN npm run build

FROM node:22.15.0-alpine3.20
WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist /app/dist

COPY --from=builder /app/.env /app/.env

EXPOSE 4173

CMD ["serve", "-s", "dist", "-l", "4173"]