FROM node:22.15.0-alpine3.20
WORKDIR /app
COPY package*.json ./
# Install only production dependencies
RUN npm ci --only=production
COPY . .
# Set NODE_ENV to production
ENV NODE_ENV=production
CMD ["npm", "start"]